[package]
name = "git-repman"
version = "0.1.0"
authors = ["Markus Røyset <maroider@protonmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.38"
clap = { version = "4.5.15", features = ["derive"] }
duct = "0.13.5"
url = "2.2.1"
